import { Container, Typography, Box, Paper, Divider, Alert } from '@mui/material';
import { Link } from 'react-router-dom';
import WarningAmberIcon from '@mui/icons-material/WarningAmber';

export default function Disclaimer() {
  return (
    <Container maxWidth="md" sx={{ py: 6 }}>
      <Paper elevation={0} sx={{ p: { xs: 3, md: 5 } }}>
        <Typography variant="h4" fontWeight={700} gutterBottom>
          Disclaimer
        </Typography>
        <Typography variant="body2" color="text.secondary" gutterBottom>
          Last updated: February 2026
        </Typography>
        <Divider sx={{ my: 3 }} />

        <Alert severity="warning" icon={<WarningAmberIcon />} sx={{ mb: 4 }}>
          <Typography fontWeight={600}>
            IHSS Care Guide is a workflow support tool only. It is not affiliated with, endorsed
            by, or operated by any official IHSS program, the California Department of Social Services
            (CDSS), or the Electronic Services Portal (ESP).
          </Typography>
        </Alert>

        <Box sx={{ '& h6': { mt: 4, mb: 1, fontWeight: 700 }, '& p': { mb: 2, lineHeight: 1.8 } }}>
          <Typography variant="h6">Not an Official IHSS Service</Typography>
          <Typography>
            This application is an independent tool created to help IHSS caregivers organize their
            documentation and workflows. It has no official connection to any government agency, county
            IHSS program, or the Electronic Services Portal. For official IHSS information, always refer
            to your county IHSS office or the California Department of Social Services.
          </Typography>

          <Typography variant="h6">No Guarantee of Compliance</Typography>
          <Typography>
            Using this App does not guarantee compliance with IHSS regulations, ESP requirements, or any
            other legal or administrative obligations. Timesheet submission, attendance tracking, and
            compliance verification must be performed directly through official IHSS and ESP systems.
            This App does not submit data to ESP on your behalf.
          </Typography>

          <Typography variant="h6">AI-Generated Content</Typography>
          <Typography>
            The structured notes, weekly summaries, and knowledge assistant responses generated by this
            App are produced by artificial intelligence and are provided for organizational convenience
            only. AI-generated content may contain errors, omissions, or outdated information. Always
            review AI outputs carefully before using them for any official purpose.
          </Typography>

          <Typography variant="h6">No Legal or Medical Advice</Typography>
          <Typography>
            Nothing in this App constitutes legal advice, medical advice, or professional guidance of any
            kind. For legal questions about IHSS regulations or your rights as a caregiver or recipient,
            consult a qualified attorney or your county IHSS office. For medical questions, consult a
            licensed healthcare provider.
          </Typography>

          <Typography variant="h6">Knowledge Assistant Limitations</Typography>
          <Typography>
            The knowledge assistant provides responses based on curated IHSS and ESP guidance documents.
            This information may not reflect the most current regulations or county-specific rules. Always
            verify important information with official sources before taking action.
          </Typography>

          <Typography variant="h6">Limitation of Liability</Typography>
          <Typography>
            The operators of IHSS Care Guide are not liable for any consequences arising from
            reliance on information provided by this App, including but not limited to missed deadlines,
            compliance failures, or errors in documentation. Use of this App is at your own risk.
          </Typography>

          <Typography variant="h6">Official Resources</Typography>
          <Typography>
            For official IHSS information and ESP support, please visit:
          </Typography>
          <Box component="ul" sx={{ pl: 3 }}>
            <li><Typography>California Department of Social Services: cdss.ca.gov</Typography></li>
            <li><Typography>Electronic Services Portal: etimesheets.ihss.ca.gov</Typography></li>
            <li><Typography>Your county IHSS office</Typography></li>
          </Box>
        </Box>

        <Divider sx={{ my: 3 }} />
        <Box sx={{ display: 'flex', gap: 3 }}>
          <Link to="/terms" style={{ color: 'inherit' }}>Terms of Service</Link>
          <Link to="/privacy" style={{ color: 'inherit' }}>Privacy Policy</Link>
          <Link to="/" style={{ color: 'inherit' }}>Home</Link>
        </Box>
      </Paper>
    </Container>
  );
}
